# Generated by Django 3.0.6 on 2020-05-29 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0003_auto_20200528_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
